### ISSUE TITLE
sql query

### ISSUE THREAD

**Issue by DavidRomanovizc** [DavidRomanovizc/DatingBot#6]
https://github.com/DavidRomanovizc/DatingBot/blob/253cd176a6788f7d71cedb496bd3a6227a75ad94/utils/db_api/postgres.py#L117

@vR4eslav а нормально, что у нас sql запрос не дописан? Или это такая фича?

**Comment by vR4eslav** [comment]
Фича, потому что туда через статический метод форматирования вставляется kwarg, и туда можно писать любое аргументы, которые имею совпадение в таблице :>

__________________________

A feature, because kwarg is inserted there through the static formatting method, and there you can write any arguments that have a match in the table :>
